name: Build - linux
on: 
  push:
    branches:
      - '**'
    tags:
      - 'v*'
    paths:
      - '!buildtools/docker/**'
  pull_request:
    branches:
      - main

jobs:
  build-debian10:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/wangyoucao577/ffmpeg-build/linux-debian10
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
          submodules: 'true'
          
      - name: Build
        run: |
          buildtools/scripts/build.sh
          tree build

      - uses: actions/upload-artifact@v3
        with:
          name: ffmpeg-deps-bin
          path: build/bin/
