name: Build
on: 
  push:
    branches:
      - '**'
    tags:
      - 'v*'
  pull_request:
    branches:
      - main


jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: git make pkgconf diffutils mingw-w64-x86_64-nasm mingw-w64-x86_64-gcc mingw-w64-x86_64-SDL2

      - name: Build
        run: |
          cd ffmpeg
          mkdir -p build
          ./configure --prefix=$(pwd)/build --enable-shared
          make -rj
          make install
          tree build

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ffmpeg-build
          path: ffmpeg/build/
