name: Build - linux
on: 
  push:
    branches:
      - '**'
    tags:
      - 'v*'
    paths-ignore:
      - 'buildtools/docker/**'
      - 'docs/**'
      - '.vscode/**'
      - '.devcontainer/**'
  pull_request:
    branches:
      - main

jobs:
  build-debian11:
    strategy:
      matrix:
        build_type: [Debug, Release]
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/wangyoucao577/ffmpeg-build/linux-debian11
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
          submodules: 'true'
          
      - name: Build
        run: |
          export FFMPEG_BUILD_TYPE=${{ matrix.build_type }}
          buildtools/scripts/build.sh
          tree build

      - uses: actions/upload-artifact@v3
        with:
          name: ffmpeg-deps-bin
          path: build/bin/

  test-debian11:
    needs: build-debian11
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/wangyoucao577/ffmpeg-build/linux-debian11
    steps:
      - uses: actions/checkout@v3
      - name: Download all artifacts
        uses: actions/download-artifact@v3
      - name: Test
        run: |
          tree ffmpeg-deps-bin
          chmod +x ffmpeg-deps-bin/*
          ./ffmpeg-deps-bin/ffmpeg -y -threads 1 -i ./tests/small_bunny_1080p_60fps.mp4 -c:v libsvtav1 -c:a copy out.mp4
          # ./ffmpeg-deps-bin/ffmpeg -y -threads 1 -i ./tests/small_bunny_1080p_60fps.mp4 -c:v libaom-av1 -c:a copy out.mp4
          ./ffmpeg-deps-bin/ffmpeg -y -threads 1 -i ./tests/small_bunny_1080p_60fps.mp4 -c:v libx264 -c:a libopus out.mp4
          ./ffmpeg-deps-bin/ffmpeg -y -threads 1 -i ./tests/small_bunny_1080p_60fps.mp4 -c:v libx265 -c:a libfdk_aac out.mp4
          ./ffmpeg-deps-bin/ffmpeg -y -i out.mp4 -i ./tests/small_bunny_1080p_60fps.mp4 -lavfi "libvmaf=log_fmt=xml:log_path=/dev/stdout:model_path=./ffmpeg-deps-bin/vmaf_v0.6.1.json" -f null -