name: Build - mac
on: 
  push:
    branches:
      - '**'
    tags:
      - 'v*'
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
          submodules: 'true'

      - name: Install tools
        run: |
          brew install tree

      - name: Install yasm
        run: |
          brew install yasm

      - name: Build dependencies
        run: |
          ./buildtools/scripts/build-svtav1.sh
          tree build

      - name: Build
        run: |
          export LD_LIBRARY_PATH="$(pwd)/build/lib:${LD_LIBRARY_PATH}"
          export PKG_CONFIG_PATH="$(pwd)/build/lib/pkgconfig:${PKG_CONFIG_PATH}"

          buildtools/scripts/build-ffmpeg.sh --enable-static --disable-shared
          tree build

      - uses: actions/upload-artifact@v3
        with:
          name: ffmpeg-deps-bin
          path: build/bin/
