name: Build - win
on: 
  push:
    branches:
      - '**'
    tags:
      - 'v*'
  pull_request:
    branches:
      - main


jobs:
  build:
    runs-on: windows-2022
    strategy:
      matrix:
        include:
          - { sys: mingw64, env: x86_64 }
          # - { sys: ucrt64,  env: ucrt-x86_64 }  # Experimental!
          # - { sys: clang64, env: clang-x86_64 } # Experimental!
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
          submodules: 'true'
      - uses: msys2/setup-msys2@v2
        with:
          msystem: ${{matrix.sys}}
          update: true
          install: >-
            git make pkgconf diffutils zip tree 
            mingw-w64-${{matrix.env}}-cmake mingw-w64-${{matrix.env}}-ninja
            mingw-w64-${{matrix.env}}-gcc 
            mingw-w64-${{matrix.env}}-yasm mingw-w64-${{matrix.env}}-SDL2
            mingw-w64-${{matrix.env}}-fdk-aac mingw-w64-${{matrix.env}}-opus 
            mingw-w64-${{matrix.env}}-x264 mingw-w64-${{matrix.env}}-x265 
            mingw-w64-${{matrix.env}}-aom 
            mingw-w64-${{matrix.env}}-srt

      - name: Build dependencies
        run: |
          ./buildtools/scripts/build-svtav1.sh
          tree build

      - name: Build
        run: |
          buildtools/scripts/build-ffmpeg.sh --enable-shared --enable-sdl2 --enable-libx264 --enable-libx265 --enable-libaom --enable-libfdk-aac --enable-libopus --enable-libsrt
          tree build

      # also need to package DLL dependencies
      #  by default the compliation depends on system installed openssl(libcrypto), so we need to copy it manually
      - name: Package
        run: |
          cd ffmpeg
          cd build/bin && ldd ffmpeg | grep ${{matrix.sys}} | awk '{system("cp "$3" ./")}' && cd ../..
          cd build/bin && ldd ffmpeg | grep libcrypto && cd ../..
          cd build/bin && ldd ffmpeg | grep libcrypto | awk '{system("cp "$3" ./")}' && cd ../..
          tree build

      - uses: actions/upload-artifact@v3
        with:
          name: ffmpeg-deps-bin
          path: build/bin/
