name: Build - linux
on: 
  push:
    branches:
      - '**'
    tags:
      - 'v*'
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/wangyoucao577/ffmpeg-build/linux-build
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
          submodules: 'true'

      - name: Build
        run: |
          cd ffmpeg
          mkdir -p build
          ./configure --prefix=$(pwd)/build --enable-static --disable-shared --enable-sdl2 --enable-gpl --enable-nonfree 
          make -rj
          make install

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ffmpeg-build
          path: ffmpeg/build/
